---
settings:
  name: Astra Automation
  internal:
    pdf_enabled: true
    api_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    api_enabled: true
  rss_page: rn/whats_new.html
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Astra Control Automation 문서
    url: "/index.html"
  - section: rn
  - section: intro
  - section: get-started
  - section: rest-core
  - section: endpoints
  - section: additional
  - section: workflows_infra
  - section: workflows
  - section: python
  - section: reference
  - section: information
  - title: 이전 버전
    url: "/aa-earlier-versions.html"
  - title: 법적 고지
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: 개요
      url: "/intro/overview.html"
    - title: 시작하기 전에
      url: "/get-started/before_get_started.html"
    - title: API 토큰을 가져옵니다
      url: "/get-started/get_api_token.html"
    - title: 첫 번째 API 호출
      url: "/get-started/first_call.html"
  - title: REST 구현
    links:
    - title: REST 웹 서비스
      url: "/rest-core/rest_web_services.html"
    - title: HTTP 세부 정보
      url: "/rest-core/http_details.html"
    - title: URL 형식
      url: "/rest-core/url_format.html"
  - title: 추가 고려 사항
    links:
    - title: RBAC 보안
      url: "/additional/rbac.html"
    - title: 컬렉션 작업
      url: "/additional/work_with_collections.html"
    - title: 진단 및 지원
      url: "/additional/diagnostics_support.html"
    - title: API 토큰을 취소합니다
      url: "/additional/revoke_token.html"
  - title: 리소스
    links:
    - title: REST 리소스 및 컬렉션
      url: "/rest-core/resources_collections.html"
    - title: Astra API 리소스 요약
      url: "/endpoints/resources.html"
  - title: 워크플로우
    links:
    - title: 준비
      url: "/get-started/prepare_to_use_workflows.html"
    - title: 인프라 워크플로우
      url: "/workflows_infra/workflows_infra_before.html"
    - title: 관리 워크플로
      url: "/workflows/workflows_before.html"
  - title: 파이썬
    links:
    - title: NetApp Astra Control Python SDK
      url: "/python/astra_toolkits.html"
    - title: Python을 기본으로 사용합니다
      url: "/python/python_before.html"
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: 모든 Astra 문서
