---
settings:
  name: Astra Automation
  internal:
    pdf_enabled: true
    api_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    api_enabled: true
  rss_page: rn/whats_new.html
  versions:
  - version-number: '24.02'
    url: "/astra-automation"
  - version-number: '23.10'
    url: "/astra-automation-2310"
  - version-number: '23.07'
    url: "/astra-automation-2307"
  - version-number: '23.04'
    url: "/astra-automation-2304"
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: Astra Control Automation 문서
    url: "/index.html"
  - section: rn
  - section: intro
  - section: get-started
  - title: Astra REST 구현
    entries:
    - section: rest-core
    - section: endpoints
    - section: additional
  - section: workflows_infra
  - section: workflows
  - section: python
  - section: reference
  - section: information
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
