---
sidebar: sidebar 
permalink: rn/about.html 
keywords: about, about this release, current release 
summary: 이 사이트의 설명서에서는 Astra Control REST API와 두 가지 Astra Control 구축 모델에 포함된 관련 자동화 기술에 대해 설명합니다. 
---
= 이 릴리스에 대해
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 사이트의 설명서에서는 Astra Control REST API와 두 가지 Astra Control 구축 모델에 포함된 관련 자동화 기술에 대해 설명합니다.

.릴리스 버전 관리
모든 Astra Control 릴리스에는 * YY.MM * 형식의 버전 번호가 할당됩니다. 일반적으로 이 값은 사용 가능한 연도(_YY_) 및 월(_MM_)을 기준으로 Astra 버전을 식별합니다. 예를 들어, Astra Control Center 23.07은 2023년 7월에 출시되었습니다.

.릴리스 회전수
일반적으로 Astra Control Service와 Astra Control Center의 업데이트는 동시에 수행됩니다. 하지만 과거에는 Astra Control Service의 릴리즈 주기가 가속화되었습니다. 이로 인해 주요 Astra Control Center 릴리즈 간에 하나 이상의 증분 업데이트가 발생했습니다.

.Astra Control 배포
이 사이트의 문서는 다음 Astra Control 릴리스에 적용됩니다.

* Astra Control 서비스 24.02
* Astra Control Center 24.02


이 사이트에서는 두 구축 모델의 REST API를 문서화하기 때문에 하나의 배포 모델 또는 다른 배포 모델에서만 일부 기능을 사용할 수 있습니다. 이 두 가지 간의 유의한 차이는 필요에 따라 기록됩니다.

.추가 정보
이전 Astra Control 릴리스와 현재 버전에 대한 자세한 내용은 다음 페이지 및 사이트를 참조하십시오.

* link:../rn/whats_new.html["Astra Control REST API의 새로운 기능"]
* link:../endpoints/resources.html["REST 리소스 및 엔드포인트"]
* https://docs.netapp.com/us-en/astra-control-center/["Astra Control Center 24.02 설명서"^]
* https://docs.netapp.com/us-en/astra-control-service/["Astra Control Service 24.02 설명서"^]
* link:../rn/earlier-versions.html["이전 버전의 Astra Automation 설명서"]


.문서 개선에 도움을 주세요
NetApp 설명서에 관한 알림을 보려면 Twitter * @NetAppDoc * 를 팔로우하십시오. 또한 이(가) 되어 피드백을 제공할 수도 있습니다 link:https://docs.netapp.com/us-en/contribute/["GitHub 기고자입니다"^] 또는 _doccomments@netapp.com_ 으로 이메일을 보내주십시오.
