---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords: whats new, enhancements, new features 
summary: NetApp은 새로운 기능, 개선 사항 및 버그 수정을 제공하기 위해 Astra Control REST API를 정기적으로 업데이트합니다. 
---
= Astra Control REST API의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp은 새로운 기능, 개선 사항 및 버그 수정을 제공하기 위해 Astra Control REST API를 정기적으로 업데이트합니다.



== 2022년 8월 10일(22.08)

이 릴리스는 REST API의 확장 및 업데이트뿐 아니라 향상된 보안 및 관리 기능도 포함합니다.



=== 새로운 고급 Astra 리소스

인증서 *, * 그룹 * 및 * AppMirror * 의 세 가지 새로운 리소스 유형이 추가되었습니다. 또한 여러 기존 리소스의 버전이 업데이트되었습니다.



=== LDAP 인증

선택적으로 Astra Control Center를 LDAP 서버와 통합하여 선택한 Astra 사용자를 인증하도록 구성할 수 있습니다. 을 참조하십시오 link:../workflows_infra/ldap_prepare.html["LDAP 구성"] 를 참조하십시오.



=== 향상된 실행 후크

실행 후크에 대한 지원이 Astra Control 21.12 릴리스와 함께 추가되었습니다. 기존의 사전 스냅샷 및 사후 스냅샷 실행 후크뿐만 아니라, 이제 22.08 릴리즈를 통해 다음과 같은 유형의 실행 후크를 구성할 수 있습니다.

* 사전 백업
* 백업 후
* 사후 복원


이제 Astra Control을 통해 여러 실행 후크에 동일한 스크립트를 사용할 수 있습니다.



=== SnapMirror를 사용한 애플리케이션 복제

이제 NetApp SnapMirror 기술을 사용하여 클러스터 간에 데이터 및 애플리케이션 변경사항을 복제할 수 있습니다. 향상된 기능은 비즈니스 연속성 및 복구 기능을 개선하는 데 사용할 수 있습니다.

.관련 정보
* https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html["Astra Control Center: 새로운 기능"^]
* https://docs.netapp.com/us-en/astra-control-service/release-notes/whats-new.html["Astra Control Service: 새로운 기능"^]




== 2022년 4월 26일(22.04)

이 릴리스는 REST API의 확장 및 업데이트뿐 아니라 향상된 보안 및 관리 기능도 포함합니다.



=== 새로운 고급 Astra 리소스

패키지 * 와 * 업그레이드 * 의 두 가지 새로운 리소스 유형이 추가되었습니다. 또한 여러 기존 리소스의 버전이 업그레이드되었습니다.



=== 네임스페이스 세분화를 통해 RBAC 강화

연결된 사용자에게 역할을 바인딩하는 경우 사용자가 액세스할 수 있는 네임스페이스를 제한할 수 있습니다. Role Binding API * 참조 및 를 참조하십시오 link:../additional/rbac.html["RBAC 보안"] 를 참조하십시오.



=== 버킷 제거

버킷이 더 이상 필요하지 않거나 제대로 작동하지 않을 경우 이를 제거할 수 있습니다.



=== Cloud Volumes ONTAP 지원

이제 Cloud Volumes ONTAP가 스토리지 백엔드로 지원됩니다.



=== 추가 제품 개선 사항

두 Astra Control 제품 구현에 대한 몇 가지 추가 개선 사항은 다음과 같습니다.

* Astra Control Center의 일반적인 침투입니다
* AKS의 프라이빗 클러스터
* Kubernetes 1.22 지원
* VMware Tanzu 포트폴리오 지원


Astra Control Center 및 Astra Control Service 문서 사이트에서 * 새로운 기능 * 페이지를 참조하십시오.

.관련 정보
* https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html["Astra Control Center: 새로운 기능"^]
* https://docs.netapp.com/us-en/astra-control-service/release-notes/whats-new.html["Astra Control Service: 새로운 기능"^]




== 2021년 12월 14일(21.12)

이 릴리스에는 향후 릴리즈 업데이트를 통해 Astra Control의 발전을 더욱 잘 지원하기 위해 문서 구조의 변경 사항과 함께 REST API 확장이 포함되어 있습니다.



=== Astra Control의 각 릴리스에 대한 Astra 자동화 문서를 분리합니다

Astra Control의 모든 릴리스에는 특정 릴리스의 기능에 맞게 향상되고 조정된 고유한 REST API가 포함되어 있습니다. Astra Control REST API의 각 릴리스에 대한 문서는 이제 관련 GitHub 콘텐츠 저장소와 함께 자체 전용 웹 사이트에서 제공됩니다. 주 문서 사이트입니다 https://docs.netapp.com/us-en/astra-automation/["Astra 제어 자동화"^] 항상 최신 릴리스에 대한 설명서를 포함합니다. 을 참조하십시오 link:../aa-earlier-versions.html["이전 버전의 Astra Control Automation 설명서"] 이전 릴리즈에 대한 자세한 내용은.



=== REST 리소스 유형의 확장

REST 리소스 유형의 수는 실행 후크와 스토리지 백엔드에 중점을 두고 계속 확장됩니다. 새로운 리소스에는 계정, 실행 후크, 후크 소스, 실행 후크 재정의, 클러스터 노드, 관리 스토리지 백엔드, 네임스페이스, 스토리지 디바이스 및 스토리지 노드 을 참조하십시오 link:../endpoints/resources.html["리소스"] 를 참조하십시오.



=== NetApp Astra Control Python SDK

NetApp Astra Control Python SDK는 오픈 소스 패키지로서, Astra Control 환경을 위한 자동화 코드를 더욱 쉽게 개발할 수 있도록 지원합니다. 핵심 요소는 REST API 호출의 복잡성을 추상화하는 일련의 클래스가 포함된 Astra SDK입니다. 또한 Python 클래스를 래핑하고 추상화하여 특정 관리 작업을 실행하는 툴킷 스크립트가 있습니다. 을 참조하십시오 link:../python/astra_toolkits.html["NetApp Astra Control Python SDK"] 를 참조하십시오.



== 2021년 8월 5일(21.08)

이 릴리스에는 새로운 Astra 배포 모델 및 REST API의 주요 확장이 포함되어 있습니다.



=== Astra Control Center 배포 모델

이 릴리즈에는 퍼블릭 클라우드 서비스로 제공되는 기존 Astra Control Service 오퍼링 외에도 Astra Control Center 온프레미스 구축 모델도 포함되어 있습니다. 사이트에 Astra Control Center를 설치하여 로컬 Kubernetes 환경을 관리할 수 있습니다. 두 Astra Control 배포 모델은 동일한 REST API를 공유하며, 설명서에 명시된 바와 같이 약간의 차이가 있습니다.



=== REST 리소스 유형의 확장

Astra Control REST API를 통해 액세스할 수 있는 리소스의 수가 크게 확장되었으며, 새로운 리소스 중 다수가 사내 Astra Control Center 오퍼링을 위한 기반을 제공하고 있습니다. 새로운 리소스에는 ASUP, 권한, 기능, 라이센스, 설정, 가입형, 버킷, 클라우드, 클러스터, 관리 클러스터, 스토리지 백엔드 및 스토리지 클래스 을 참조하십시오 link:../endpoints/resources.html["리소스"] 를 참조하십시오.



=== Astra 구축을 지원하는 추가 엔드포인트에는

확장된 REST 리소스 외에도 Astra Control 구축을 지원하는 데 사용할 수 있는 여러 가지 새로운 API 엔드포인트가 있습니다.

OpenAPI 지원:: OpenAPI 엔드포인트는 현재 OpenAPI JSON 문서 및 기타 관련 리소스에 대한 액세스를 제공합니다.
OpenMetrics 지원:: OpenMetrics 엔드포인트는 OpenMetrics 리소스를 통해 계정 메트릭에 액세스할 수 있습니다.




== 2021년 4월 15일(21.04)

이 릴리즈에는 다음과 같은 새로운 기능과 향상된 기능이 포함되어 있습니다.



=== REST API 소개

Astra Control REST API는 Astra Control Service 오퍼링과 함께 사용할 수 있습니다. REST 기술과 현재의 모범 사례를 기반으로 개발되었으며 API는 Astra 구축을 자동화하기 위한 기반을 제공하며 다음과 같은 기능과 이점을 제공합니다.

리소스:: 14개의 REST 리소스 유형을 사용할 수 있습니다.
API 토큰 액세스:: REST API에 대한 액세스는 Astra 웹 사용자 인터페이스에서 생성할 수 있는 API 액세스 토큰을 통해 제공됩니다. API 토큰은 API에 대한 보안 액세스를 제공합니다.
컬렉션 지원:: 리소스 컬렉션에 액세스하는 데 사용할 수 있는 다양한 쿼리 매개 변수 집합이 있습니다. 지원되는 일부 작업에는 필터링, 정렬 및 페이지 매김이 포함됩니다.

