---
sidebar: sidebar 
permalink: workflows_infra/wf_add_cluster.html 
keywords:  
summary: 클러스터를 추가하면 Astra에서 관리할 수 있습니다. 
---
= 자격 증명을 사용하여 클러스터를 추가합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
클러스터를 추가하면 Astra에서 관리할 수 있습니다. Astra 22.11 릴리즈부터 Astra Control Center와 Astra Control Service가 모두 포함된 클러스터를 추가할 수 있습니다.


NOTE: 주요 클라우드 공급자(AKS, EKS, GKE) 중 하나에서 Kubernetes 서비스를 사용할 때는 클러스터를 추가할 필요가 없습니다.



== 단계 1: kubeconfig 파일을 얻습니다

Kubernetes 관리자 또는 서비스로부터 * kubconfig * 파일의 복사본을 얻어야 합니다.



== 단계 2: kubeconfig 파일을 준비합니다

kubecononfig * 파일을 사용하기 전에 다음 작업을 수행해야 합니다.

. 파일을 YAML 형식에서 JSON으로 변환:
+
YAML 형식의 kubecononfig 파일을 받으면 JSON으로 변환해야 합니다.

. Base64에서 JSON 인코딩:
+
base64에서 JSON 파일을 인코딩해야 합니다.



.예
다음은 kubecononfig 파일을 YAML에서 JSON으로 변환한 후 base64로 인코딩하는 예입니다.

`yq -o=json ~/.kube/config | base64`



== 3단계: 클라우드를 선택합니다

워크플로우를 수행합니다 link:../workflows_infra/wf_list_clouds.html["구름 목록을 표시합니다"] 클러스터를 추가할 클라우드를 선택합니다.


NOTE: 선택할 수 있는 유일한 클라우드는 * 프라이빗 * 클라우드입니다.



== 4단계: 자격 증명을 만듭니다

kubecononfig 파일을 사용하여 자격 증명을 생성하려면 다음 REST API 호출을 수행합니다.

.HTTP 메서드 및 끝점입니다
이 REST API 호출은 다음과 같은 메소드와 엔드포인트를 사용합니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 게시 | /accounts/{account_id}/core/v1/credentials 
|===
.컬의 예
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/core/v1/credentials" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.JSON 입력 예
[source, json]
----
{
  "type" :  "application/astra-credential",
  "version" : "1.1",
  "name" : "Cloud One",
  "keyType" : "kubeconfig",
  "keyStore" : {
    "base64": encoded_kubeconfig
  },
  "valid" : "true"
}
----


== 5단계: 클러스터를 추가합니다

다음 REST API 호출을 수행하여 클러스터를 클라우드에 추가합니다. 의 값 `credentialID` 입력 필드는 이전 단계의 REST API 호출에서 얻어집니다.

.HTTP 메서드 및 끝점입니다
이 REST API 호출은 다음과 같은 메소드와 엔드포인트를 사용합니다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 게시 | /accounts/{account_id}/topology/v1/cloud/{cloud_id}/cluster 
|===
.컬의 예
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/topology/v1/clouds/<CLOUD_ID>/clusters" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data  @JSONinput
----
.JSON 입력 예
[source, json]
----
{
  "type" :  "application/astra-cluster",
  "version" : "1.1",
  "credentialID": credential_id
}
----