---
sidebar: sidebar 
permalink: workflows_infra/wf_ldap_disable_reset.html 
keywords:  
summary: Astra Control Center 배포용으로 필요에 따라 수행할 수 있는 두 가지 관련 관리 작업은 선택 사항입니다. LDAP 인증을 전역적으로 비활성화하고 LDAP 구성을 재설정할 수 있습니다. 
---
= LDAP를 비활성화하고 재설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Control Center 배포용으로 필요에 따라 수행할 수 있는 두 가지 관련 관리 작업은 선택 사항입니다. LDAP 인증을 전역적으로 비활성화하고 LDAP 구성을 재설정할 수 있습니다.

두 워크플로우 모두 Astra.account.ldap.astra 설정에 대한 ID가 필요합니다. 설정 ID를 검색하는 방법에 대한 자세한 내용은 * LDAP 서버 구성 * 에 포함되어 있습니다. 을 참조하십시오 link:../workflows_infra/wf_ldap_configure_server.html#3-retrieve-the-uuid-of-the-ldap-setting["LDAP 설정의 UUID를 조회한다"] 를 참조하십시오.

* link:../workflows_infra/wf_ldap_disable_reset.html#disable-ldap-authentication["LDAP 인증을 비활성화합니다"]
* link:../workflows_infra/wf_ldap_disable_reset.html#reset-the-ldap-authentication-configuration["LDAP 인증 구성을 재설정합니다"]




== LDAP 인증을 비활성화합니다

다음 REST API 호출을 수행하여 특정 Astra 구축에 대한 LDAP 인증을 전역적으로 비활성화할 수 있습니다. 이 호출은 Astra.account.ldap 설정을 업데이트하고 IsEnabled 값은 false로 설정된다.

[cols="1,6"]
|===
| HTTP 메소드 | 경로 


| 를 누릅니다 | /accounts/{account_id}/core/v1/settings/{setting_id} 
|===


===== JSON 입력 예

[source, json]
----
{
  "type": "application/astra-setting",
  "version": "1.0",
  "desiredConfig": {
    "connectionHost": "myldap.example.com",
    "credentialId": "3bd9c8a7-f5a4-4c44-b778-90a85fc7d154",
    "groupBaseDN": "OU=groups,OU=astra,DC=example,DC=com",
    "isEnabled": "false",
    "port": 686,
    "secureMode": "LDAPS",
    "userBaseDN": "OU=users,OU=astra,DC=example,dc=com",
    "userSearchFilter": "((objectClass=User))",
    "vendor": "Active Directory"
    }
}
----
[source, curl]
----
curl --location -i --request PUT --data @JSONinput 'https://astra.example.com/accounts/<ACCOUNT_ID>/core/v1/settings/<SETTING_ID>' --header 'Content-Type: application/astra-setting+json' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----
호출이 성공하면 HTTP 204 응답이 반환됩니다. 필요에 따라 구성 설정을 다시 검색하여 변경을 확인할 수 있습니다.



== LDAP 인증 구성을 재설정합니다

다음 REST API 호출을 수행하여 LDAP 서버에서 Astra 연결을 끊고 Astra에서 LDAP 구성을 재설정할 수 있습니다. 호에는 Astra.account.ldap 설정이 업데이트되고 connectionHost 값이 지워집니다.

IsEnabled의 값도 false로 설정되어야 합니다. 재설정 통화를 하기 전에 또는 재설정 통화를 하기 위해 이 값을 설정할 수 있습니다. 두 번째 경우는 connectionHost를 지워지고 동일한 재설정 호출에서 IsEnabled를 false로 설정해야 합니다.


CAUTION: 이는 중단을 야기하는 작업이므로 주의하여 진행해야 합니다. 가져온 LDAP 사용자 및 그룹이 모두 삭제됩니다. 또한 Astra Control Center에서 만든 관련 Astra 사용자, 그룹 및 roleBindings(LDAP 유형)도 모두 삭제합니다.

[cols="1,6"]
|===
| HTTP 메소드 | 경로 


| 를 누릅니다 | /accounts/{account_id}/core/v1/settings/{setting_id} 
|===


===== JSON 입력 예

[source, json]
----
{
  "type": "application/astra-setting",
  "version": "1.0",
  "desiredConfig": {
    "connectionHost": "",
    "credentialId": "3bd9c8a7-f5a4-4c44-b778-90a85fc7d154",
    "groupBaseDN": "OU=groups,OU=astra,DC=example,DC=com",
    "isEnabled": "false",
    "port": 686,
    "secureMode": "LDAPS",
    "userBaseDN": "OU=users,OU=astra,DC=example,dc=com",
    "userSearchFilter": "((objectClass=User))",
    "vendor": "Active Directory"
    }
}
----
다음 사항에 유의하십시오.

* LDAP 서버를 변경하려면 위의 예와 같이 "connectHost"를 null 값으로 변경하는 LDAP를 해제하고 재설정해야 합니다.


[source, curl]
----
curl --location -i --request PUT --data @JSONinput 'https://astra.example.com/accounts/<ACCOUNT_ID>/core/v1/settings/<SETTING_ID>' --header 'Content-Type: application/astra-setting+json' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----
호출이 성공하면 HTTP 204 응답이 반환됩니다. 선택적으로 구성을 다시 검색하여 변경을 확인할 수 있습니다.
