---
sidebar: sidebar 
permalink: intro/overview.html 
keywords: overview, introduction, features, benefits, deployment models, object model, query parameters, automation, family 
summary: Astra Control Center 및 Astra Control Service는 공통 REST API를 제공하여 Curl과 같은 프로그래밍 언어 또는 유틸리티를 통해 직접 액세스할 수 있습니다. API의 주요 특징 및 이점은 여러 가지가 있습니다. 
---
= 기능 및 이점 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Control Center 및 Astra Control Service는 공통 REST API를 제공하여 Curl과 같은 프로그래밍 언어 또는 유틸리티를 통해 직접 액세스할 수 있습니다. API의 주요 특징 및 이점은 다음과 같습니다.


NOTE: REST API에 액세스하려면 먼저 Astra 웹 사용자 인터페이스에 로그인하고 API 토큰을 생성해야 합니다. 각 API 요청에 토큰을 포함해야 합니다.

Astra Control API는 REST 기술과 최신 Best Practice를 사용하여 만들어졌습니다. 코어 기술에는 HTTP, JSON 및 RBAC가 포함됩니다.

Astra Control Service는 퍼블릭 클라우드 환경 내에서 사용되고, Astra Control Center는 사내 배포용으로 사용됩니다. 이러한 구축 모델을 모두 지원하는 하나의 REST API가 있습니다.

리소스 맵에 액세스하는 데 사용되는 외부 REST 엔드포인트는 Astra 서비스에서 내부적으로 유지 관리하는 일관된 오브젝트 모델에 있습니다. 객체 모델은 API 작업과 응답을 명확하게 정의하는 데 도움이 되는 ER(Entity-relationship) 모델링을 사용하여 설계되었습니다.

REST API는 리소스 컬렉션에 액세스하는 데 사용할 수 있는 풍부한 쿼리 매개 변수 집합을 제공합니다. 지원되는 일부 작업에는 필터링, 정렬 및 페이지 매김이 포함됩니다.

Astra 웹 사용자 인터페이스의 설계는 REST API와 일치하므로 두 액세스 경로와 사용자 경험 간에 일관성이 있습니다.

Astra Control REST API는 시스템 이벤트 및 사용자 알림을 포함하여 강력한 디버깅 및 문제 확인 기능을 제공합니다.

자동화 코드 개발을 지원하기 위해 일련의 워크플로우가 제공됩니다. 워크플로우는 인프라 및 관리의 두 가지 범주로 구성됩니다.

REST API에 직접 액세스하는 것 외에도 REST API를 기반으로 하는 다른 자동화 기술을 사용할 수 있습니다.

Astra Control Automation 문서는 대규모 Astra 제품군 문서의 일부입니다. 을 참조하십시오 https://docs.netapp.com/us-en/astra-family/["Astra 문서"^] 를 참조하십시오.
