---
sidebar: sidebar 
permalink: rest-core/resources_collections.html 
keywords: concepts 
summary:  
---
= 리소스 및 컬렉션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Control REST API는 리소스 인스턴스 및 리소스 인스턴스 컬렉션에 대한 액세스를 제공합니다.


NOTE: 개념적으로 REST * 리소스 * 는 OOP(개체 지향 프로그래밍) 언어 및 시스템에 정의된 * 개체 * 와 유사합니다. 때때로 이러한 용어는 서로 바꿔서 사용할 수 있습니다. 그러나 일반적으로 "리소스"는 외부 REST API의 컨텍스트에서 사용하는 반면 "개체"는 서버에 저장된 해당 상태 저장 인스턴스 데이터에 사용됩니다.



== Astra 리소스의 속성

Astra Control REST API는 RESTful 설계 원칙을 준수합니다. 각 Astra 리소스 인스턴스는 잘 정의된 리소스 유형을 기반으로 생성됩니다. 같은 형식의 리소스 인스턴스 집합을 * 컬렉션 * 이라고 합니다. API 호출은 개별 리소스 또는 리소스 모음에 대해 작동합니다.



===== 리소스 유형

Astra Control REST API에 포함된 리소스 유형은 다음과 같은 특성을 갖습니다.

* 모든 리소스 유형은 스키마(일반적으로 JSON)를 사용하여 정의됩니다.
* 모든 리소스 스키마에는 리소스 유형과 버전이 포함됩니다
* 리소스 유형은 전역적으로 고유합니다




===== 리소스 인스턴스

Astra Control REST API를 통해 사용 가능한 리소스 인스턴스의 특징은 다음과 같습니다.

* 리소스 인스턴스는 단일 리소스 유형에 따라 만들어집니다
* 리소스 유형은 미디어 유형 값을 사용하여 표시됩니다
* 인스턴스는 Astra 서비스에서 유지 관리하는 상태 저장 데이터로 구성됩니다
* 각 인스턴스는 고유하고 오래 지속되는 URL을 통해 액세스할 수 있습니다
* 리소스 인스턴스에 둘 이상의 표현이 있을 수 있는 경우 다양한 미디어 유형을 사용하여 원하는 표현을 요청할 수 있습니다




===== 리소스 컬렉션

Astra Control REST API를 통해 사용 가능한 리소스 수집에는 다음과 같은 특성이 있습니다.

* 단일 리소스 형식의 리소스 인스턴스 집합을 컬렉션이라고 합니다
* 리소스 컬렉션에는 고유하고 오래 지속되는 URL이 있습니다




===== 인스턴스 식별자

모든 리소스 인스턴스는 만들 때 식별자가 할당됩니다. 이 식별자는 128비트 UIDv4 값입니다. 할당된 UUIDv4 값은 전역적으로 고유하며 변경할 수 없습니다. 새 인스턴스를 만드는 API 호출을 실행하면 관련 ID가 있는 URL이 HTTP 응답의 "위치" 헤더에서 호출자에게 반환됩니다. 식별자를 추출하여 리소스 인스턴스를 참조할 때 후속 호출에 사용할 수 있습니다.


NOTE: 리소스 식별자는 컬렉션에 사용되는 기본 키입니다.



== Astra 리소스의 공통 구조

모든 Astra Control 리소스는 공통 구조를 사용하여 정의됩니다.



===== 공통 데이터

모든 Astra 리소스에는 다음 표에 나와 있는 키 값이 포함되어 있습니다.

[cols="15,85"]
|===
| 키 | 설명 


| 유형 | 자원 유형 * 이라고 하는 전역적으로 고유한 자원 유형입니다. 


| 버전 | 리소스 버전*이라고 하는 버전 식별자입니다. 


| ID입니다 | 리소스 식별자 * 라고 하는 전역 고유 식별자입니다. 


| 메타데이터 | 사용자 및 시스템 레이블을 비롯한 다양한 정보를 포함하는 JSON 개체입니다. 
|===


===== 메타데이터 개체입니다

각 Astra 리소스에 포함된 메타데이터 JSON 개체에는 다음 표에 나와 있는 키 값이 포함됩니다.

[cols="15,85"]
|===
| 키 | 설명 


| 라벨 | 리소스와 연결된 클라이언트 지정 레이블의 JSON 배열입니다. 


| CreationTimestamp 를 클릭합니다 | JSON 문자열에는 리소스가 생성된 시점을 나타내는 타임스탬프가 포함되어 있습니다. 


| modificationTimestamp | ISO-8601 형식의 타임 스탬프가 포함된 JSON 문자열로, 리소스가 마지막으로 변경된 시기를 나타냅니다. 


| 생성 시 | 리소스를 생성한 사용자 ID의 UUIDv4 식별자가 포함된 JSON 문자열입니다. 내부 시스템 구성 요소에 의해 리소스가 생성되었고 생성 엔티티와 연관된 UUID가 없는 경우 * null * UUID가 사용됩니다. 
|===


===== 리소스 상태입니다

선택한 리소스 수명 주기 전환을 조정하고 액세스를 제어하는 데 사용되는 '상태' 값입니다.
