---
sidebar: sidebar 
permalink: workflows/wf_list_unman_apps.html 
keywords:  
summary:  
---
= 관리되지 않는 앱을 나열합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
현재 Astra에서 관리하지 않는 애플리케이션을 나열할 수 있습니다. 이 작업은 관리할 앱을 선택하는 과정에서 수행할 수 있습니다.


NOTE: 이러한 워크플로에 사용되는 REST 끝점은 기본적으로 모든 Astra 애플리케이션을 반환합니다. API 호출에서 'filter' query 매개 변수를 사용하여 관리되지 않는 앱만 반환하도록 요청할 수 있습니다. 또는 필터 매개 변수를 생략하여 모든 앱을 반환한 다음 출력에서 'managedState' 필드를 검사하여 '관리되지 않는' 상태에 있는 앱을 확인할 수도 있습니다.



== 관리되는 상태가 관리되지 않는 것과 동일한 앱만 나열합니다

이 워크플로에서는 필터 쿼리 매개 변수를 사용하여 관리되지 않는 앱만 반환합니다.



=== 관리되지 않는 응용 프로그램을 나열합니다

다음과 같은 REST API 호출을 수행한다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 가져오기 | /account/{AccountID}/topology/v1/apps 
|===


===== 추가 입력 매개변수

모든 REST API 호출에서 일반적으로 사용되는 매개 변수 외에도 이 단계의 curl 예제에도 다음 매개 변수가 사용됩니다.

[cols="25,10,10,55"]
|===
| 매개 변수 | 유형 | 필수 요소입니다 | 설명 


| 필터 | 쿼리 | 아니요 | 필터를 사용하여 반환할 앱을 지정합니다. 


| 포함 | 쿼리 | 아니요 | 필요에 따라 응답에서 반환할 값을 선택합니다. 
|===


===== curl 예제: 관리되지 않는 앱에 대한 이름, id 및 managedState를 반환합니다

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?filter=managedState%20eq%20'unmanaged'&include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== JSON 출력 예

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ]
  ],
  "metadata": {}
}
----


== 모든 앱을 나열하고 관리되지 않는 앱을 선택합니다

이 워크플로는 모든 앱을 반환합니다. 관리되지 않는 출력을 확인하려면 출력을 검사해야 합니다.



=== 모든 응용 프로그램을 나열합니다

다음과 같은 REST API 호출을 수행한다.

[cols="25,75"]
|===
| HTTP 메소드 | 경로 


| 가져오기 | /account/{AccountID}/topology/v1/apps 
|===


===== 추가 입력 매개변수

모든 REST API 호출에서 일반적으로 사용되는 매개 변수 외에도 이 단계의 curl 예제에도 다음 매개 변수가 사용됩니다.

[cols="25,10,10,55"]
|===
| 매개 변수 | 유형 | 필수 요소입니다 | 설명 


| 포함 | 쿼리 | 아니요 | 필요에 따라 응답에서 반환할 값을 선택합니다. 
|===


===== curl 예: 모든 앱에 대한 모든 데이터를 반환합니다

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== curl 예제: 모든 앱에 대해 name , id 및 managedState 를 반환합니다

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/apps?include=name,id,managedState' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== JSON 출력 예

[source, json]
----
{
  "items": [
    [
      "maria",
      "eed19f78-0884-4792-bb7a-313258c6b0b1",
      "unmanaged"
    ],
    [
      "mariadb-mariadb",
      "8da20fff-c69c-4170-bb0d-e4f91c5a1333",
      "managed"
    ],
    [
      "test-postgres-app",
      "1ee6235b-cda1-45cb-8d4c-630bdb8b41a5",
      "unmanaged"
    ],
    [
      "postgres1-postgresql",
      "e591ee59-ea90-4a9f-8e6c-d2b6e8647096",
      "unmanaged"
    ],
    [
      "kube-system",
      "077a2f73-4b51-4d04-8c6c-f63b3b069755",
      "unmanaged"
    ],
    [
      "trident",
      "5b6fc28f-e308-4653-b9d2-6d66a764d2e1",
      "unmanaged"
    ],
    [
      "postgres1-postgresql-clone",
      "06be05c5-763e-4d73-bd06-1f27f5f2e130",
      "unmanaged"
    ],
    [
      "davidns-postgres-app",
      "11e046b7-ec64-4184-85b3-debcc3b1da4d",
      "managed"
    ]
  ],
  "metadata": {}
}
----


=== 관리되지 않는 응용 프로그램을 선택합니다

API 호출 출력을 검토하고 'unmanaged'와 같은 'managedState'가 있는 앱을 수동으로 선택합니다.
