---
sidebar: sidebar 
permalink: workflows/workflows_before.html 
keywords:  
summary:  
---
= 시작하기 전에
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra 관리 클러스터 내에서 애플리케이션을 관리하는 과정에서 이러한 워크플로우를 사용할 수 있습니다.


NOTE: 이러한 워크플로우는 NetApp이 언제든지 확장 및 개선할 수 있으므로 정기적으로 검토해야 합니다.



== 일반 준비

Astra 워크플로를 사용하기 전에 반드시 검토하십시오 link:../get-started/prepare_to_use_workflows.html["워크플로우 사용을 준비하십시오"].



== 워크플로 범주

관리 워크플로는 원하는 항목을 쉽게 찾을 수 있도록 여러 범주로 구성됩니다.

[cols="25,75"]
|===
| 범주 | 설명 


| 애플리케이션 제어 | 이러한 워크플로를 통해 관리되는 응용 프로그램과 관리되지 않는 응용 프로그램을 제어할 수 있습니다. 앱을 나열하고 관리되는 앱을 만들고 제거할 수 있습니다. 


| 애플리케이션 보호 | 이러한 워크플로우를 사용하여 스냅샷과 백업을 통해 관리되는 애플리케이션을 보호할 수 있습니다. 


| 앱 클론 생성 및 복원 | 이러한 워크플로에서는 관리되는 애플리케이션을 클론 복제 및 복원하는 방법을 설명합니다. 


| 지원 | 일반 Kubernetes 환경뿐만 아니라 애플리케이션을 디버깅 및 지원하는 데 사용할 수 있는 몇 가지 워크플로우가 있습니다. 
|===


== 추가 고려 사항

관리 워크플로를 사용할 때는 몇 가지 추가 고려 사항이 있습니다.



=== 앱 복제

애플리케이션 클론 생성 시 고려해야 할 몇 가지 사항은 다음과 같습니다. 아래 설명된 매개 변수는 JSON 입력의 일부입니다.

소스 클러스터 식별자입니다:: '소스 클러스터 ID' 값은 항상 원래 앱이 설치된 클러스터를 식별합니다.
클러스터 식별자입니다:: 'clusterID' 값은 새 앱을 설치할 클러스터를 식별합니다.
+
--
* 같은 클러스터 내에서 복제하면 clusterID와 sourceClusterID가 같은 값을 갖습니다.
* 클러스터 간에 클론을 생성할 때 두 값은 서로 다르며 클러스터 ID는 타겟 클러스터의 ID가 되어야 합니다.


--
네임스페이스:: 네임스페이스 값은 원본 소스 앱과 달라야 합니다. 또한 클론의 네임스페이스가 존재할 수 없으며 Astra에서 생성합니다.
백업 및 스냅샷:: "backupID" 또는 "shapshotID" 매개 변수를 사용하여 기존 백업 또는 스냅샷에서 응용 프로그램을 복제할 수도 있습니다. 백업 또는 스냅샷을 제공하지 않는 경우 먼저 애플리케이션의 백업을 생성한 다음 백업에서 클론을 생성합니다.




==== 앱을 복원하는 중입니다

다음은 응용 프로그램을 복원할 때 고려해야 할 몇 가지 사항입니다.

* 애플리케이션 복구는 클론 작업과 매우 유사합니다.
* 앱을 복구할 때는 백업 또는 스냅샷을 제공해야 합니다.

