---
sidebar: sidebar 
permalink: python/astra_toolkits.html 
keywords:  
summary:  
---
= NetApp Astra Control Python SDK
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Astra Control Python SDK는 Astra Control 구축을 자동화하는 데 사용할 수 있는 오픈 소스 패키지입니다. 또한 이 패키지는 Astra Control REST API에 대해 학습하는 귀중한 리소스로서, 자신의 자동화 플랫폼을 구축하는 데 사용될 수 있습니다.


NOTE: 간소화를 위해 NetApp Astra Control Python SDK를 나머지 페이지 전체에서 * SDK * 라고 부릅니다.



== 두 가지 관련 소프트웨어 도구

SDK에는 Astra Control REST API에 액세스할 때 서로 다른 추상화 수준에서 작동하는 두 가지 서로 다른 관련 툴이 포함되어 있습니다.



==== Astra SDK

Astra SDK는 핵심 플랫폼 기능을 제공합니다. 기본 REST API 호출을 추상화하는 Python 클래스 집합이 포함되어 있습니다. 이 클래스는 앱, 백업, 스냅샷 및 클러스터를 포함한 다양한 Astra Control 리소스에 대한 관리 작업을 지원합니다.

Astra SDK는 패키지의 한 부분으로, 하나의 "astraSDK.py" 파일로 제공됩니다. 이 파일을 사용자 환경으로 가져오고 클래스를 직접 사용할 수 있습니다.


NOTE: NetApp Astra Control Python SDK * (또는 SDK)는 전체 패키지의 이름입니다. Astra SDK * 는 단일 파일 'astraSDK.py'의 핵심 Python 클래스를 나타냅니다.



==== 툴킷 스크립트입니다

Astra SDK 파일 외에 toolkit.py 스크립트도 사용할 수 있다. 이 스크립트는 Python 함수로 내부적으로 정의된 개별 관리 작업에 대한 액세스를 제공하여 높은 수준의 추상화로 작동합니다. 이 스크립트는 Astra SDK를 가져오고 필요에 따라 클래스를 호출합니다.



== 액세스 방법

다음과 같은 방법으로 SDK에 액세스할 수 있습니다.



==== Python 패키지

SDK는 에서 확인할 수 있습니다 https://pypi.org/["Python 패키지 색인"^] 이름아래 * NetApp-Astra-툴킷 *. 패키지에 버전 번호가 할당되며 필요에 따라 계속 업데이트됩니다. PIP* 패키지 관리 유틸리티를 사용하여 사용자 환경에 패키지를 설치해야 합니다.

을 참조하십시오 https://pypi.org/project/netapp-astra-toolkits/["PyPI: NetApp Astra Control Python SDK"^] 를 참조하십시오.



==== GitHub 소스 코드입니다

SDK 소스 코드는 GitHub에서도 사용할 수 있습니다. 리포지토리에는 다음이 포함됩니다.

* astraSDK.py (Python 수업이 있는 Astra SDK)
* toolkit.py(상위 수준 함수 기반 스크립트)
* 자세한 설치 요구 사항 및 지침
* 설치 스크립트
* 추가 문서


를 클론 복제할 수 있습니다 https://github.com/NetApp/netapp-astra-toolkits["GitHub:NetApp/NetApp-Astra-툴킷"^] 로컬 환경에 리포지토리.



== 설치 및 기본 요구 사항

패키지 설치 및 사용 준비 과정에서 고려해야 할 몇 가지 옵션과 요구 사항이 있습니다.



==== 설치 옵션 요약

다음 방법 중 하나로 SDK를 설치할 수 있습니다.

* Pip을 사용하여 PyPI에서 Python 환경에 패키지를 설치합니다
* Git Hub 리포지토리를 클론하고 다음 중 하나를 수행합니다.
+
** 패키지를 Docker 컨테이너(필요한 모든 것을 포함)로 구축
** Python 클라이언트 코드에 액세스할 수 있도록 두 개의 핵심 Python 파일을 복사합니다




자세한 내용은 PyPI 및 GitHub 페이지를 참조하십시오.



==== Astra Control 환경에 대한 요구 사항

Astra SDK에서 Python 클래스를 직접 사용하거나 toolkit.py 스크립트의 함수를 사용하는 경우 Astra Control 구축 시 REST API에 액세스할 수 있습니다. 이 때문에 API 토큰과 함께 Astra 계정이 필요합니다. 을 참조하십시오 link:../get-started/before_get_started.html["시작하기 전에"] 자세한 내용은 이 설명서의 * 시작하기 * 섹션의 다른 페이지를 참조하십시오.



==== NetApp Astra Control Python SDK의 요구사항

SDK에는 로컬 Python 환경과 관련된 몇 가지 사전 요구 사항이 있습니다. 예를 들어 Python 3.5 이상을 사용해야 합니다. 또한 필요한 여러 가지 Python 패키지가 있습니다. 자세한 내용은 GitHub 리포지토리 페이지 또는 PyPI 패키지 페이지를 참조하십시오.



== 유용한 리소스 요약

다음은 시작하는 데 필요한 리소스 요약입니다.

* https://pypi.org/project/netapp-astra-toolkits/["PyPI: NetApp Astra Control Python SDK"^]
* https://github.com/NetApp/netapp-astra-toolkits["GitHub:NetApp/NetApp-Astra-툴킷"^]

