---
sidebar: sidebar 
permalink: get-started/get_api_token.html 
keywords:  
summary:  
---
= API 토큰을 가져옵니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Control REST API를 사용하려면 Astra API 토큰을 얻어야 합니다.



== 소개

API 토큰은 Astra에 호출자를 식별하며 모든 REST API 호출에 포함되어야 합니다.

* Astra 웹 사용자 인터페이스를 사용하여 API 토큰을 생성할 수 있습니다.
* 토큰과 함께 전달된 사용자 ID는 토큰을 생성하는 사용자에 의해 결정됩니다.
* 토큰은 인가 HTTP 요청 헤더에 포함되어야 합니다.
* 토큰이 생성된 후에는 만료되지 않습니다.
* Astra 웹 사용자 인터페이스에서 토큰을 취소할 수 있습니다.


.관련 정보
* link:../additional/revoke_token.html["API 토큰을 취소합니다"]




== Astra API 토큰을 생성합니다

다음 단계에서는 Astra API 토큰을 생성하는 방법을 설명합니다.

Astra 계정에 대한 자격 증명이 필요합니다.

이 작업은 Astra 웹 인터페이스에서 API 토큰을 생성합니다. 또한 API 호출 시 필요한 계정 ID도 검색해야 합니다.

.단계
. 계정 자격 증명을 사용하여 Astra에 로그인합니다.
+
Astra Control Service에 대한 다음 사이트에 액세스합니다. https://astra.netapp.io/["https://astra.netapp.io"^]

. 페이지 오른쪽 상단의 그림 아이콘을 클릭하고 * API access * 를 선택합니다.
. 페이지에서 * API 토큰 생성 * 을 클릭하고 팝업 창에서 * API 토큰 생성 * 을 클릭합니다.
. 아이콘을 클릭하여 토큰 문자열을 클립보드에 복사하고 편집기에 저장합니다.
. 동일한 페이지에서 사용할 수 있는 계정 ID를 복사하여 저장합니다.


Curl 또는 프로그래밍 언어를 통해 Astra Control REST API에 액세스할 때는 HTTP 'Authorization' 요청 헤더에 API bearer 토큰을 포함시켜야 합니다.
