---
sidebar: sidebar 
permalink: get-started/prepare_to_use_workflows.html 
keywords:  
summary:  
---
= 워크플로우 사용을 준비하십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
실제 배포와 함께 사용하기 전에 Astra 워크플로의 구성 및 형식을 숙지해야 합니다.



== 소개

Workflow _ 은(는) 특정 관리 작업 또는 목표를 달성하는 데 필요한 하나 이상의 단계 시퀀스입니다. Astra Control 워크플로우의 각 단계는 다음 중 하나입니다.

* REST API 호출(curl 및 JSON 예 등의 세부 정보 포함)
* 다른 Astra 워크플로 호출
* 기타 관련 작업(예: 필요한 설계 결정)


워크플로에는 각 작업을 수행하는 데 필요한 핵심 단계와 매개 변수가 포함됩니다. 또한 자동화 환경을 사용자 지정할 수 있는 출발점을 제공합니다.



== 공통 입력 매개변수

아래에 설명된 입력 매개 변수는 REST API 호출을 나타내는 데 사용되는 모든 curl 샘플에 공통으로 사용됩니다.


NOTE: 이러한 입력 매개 변수는 보편적으로 필요하기 때문에 개별 워크플로에서 더 이상 설명되지 않습니다. 특정 curl 예제에 추가 입력 매개 변수가 사용되는 경우 * 추가 입력 매개 변수 * 절에 설명되어 있습니다.



=== 경로 매개 변수

모든 REST API 호출에 사용되는 엔드포인트 경로에는 다음 매개 변수가 포함됩니다. 도 참조하십시오 link:../rest-core/url_format.html["URL 형식"] 를 참조하십시오.

계정 ID입니다:: API 작업이 실행되는 Astra 계정을 식별하는 UIDv4 값이다. 을 참조하십시오 link:../get-started/get_api_token.html["API 토큰을 가져옵니다"] 계정 ID를 찾는 방법에 대한 자세한 내용은 를 참조하십시오.




=== 요청 헤더

REST API 호출에 따라 몇 가지 요청 헤더를 포함해야 할 수도 있습니다.

권한 부여:: 워크플로의 모든 API 호출에는 사용자를 식별하기 위한 API 토큰이 필요합니다. '권한 부여' 요청 헤더에 토큰을 포함해야 합니다. 을 참조하십시오 link:../get-started/get_api_token.html["API 토큰을 가져옵니다"] API 토큰 생성에 대한 자세한 내용은 를 참조하십시오.
콘텐츠 유형:: HTTP POST 및 PUT 요청을 사용하여 요청 본문에 JSON이 포함된 경우 Astra 리소스를 기반으로 미디어 유형을 선언해야 합니다. 예를 들어, 관리 대상 애플리케이션에 대한 스냅샷을 생성할 때 "Content-Type:application/astra-appSnap+json" 머리글을 포함할 수 있습니다.
수락:: Astra 리소스를 기반으로 응답에서 예상하는 콘텐츠의 특정 미디어 유형을 선언할 수 있습니다. 예를 들어, 관리 대상 애플리케이션의 백업을 나열할 때 "Accept:application/astra-appBackup+json" 머리글을 포함할 수 있습니다. 그러나 간단히 하기 위해 워크플로의 curl 샘플에는 모든 미디어 유형이 적용됩니다.




== 토큰 및 식별자 표시

curl 예제에 사용된 API 토큰과 기타 ID 값은 식별 가능한 의미 없이 불투명합니다. 따라서 샘플의 가독성을 향상시키기 위해 실제 토큰 및 ID 값은 사용되지 않습니다. 대신, 다음과 같은 몇 가지 이점을 제공하는 더 작은 예약 키워드가 사용됩니다.

* CURL 및 JSON 샘플은 보다 명확하고 이해하기 쉽습니다.
* 모든 키워드는 대괄호와 대문자를 사용하여 동일한 형식을 사용하기 때문에 삽입하거나 추출할 위치와 내용을 빠르게 식별할 수 있습니다.
* 원래 매개 변수를 복사하여 실제 배포에서 사용할 수 없으므로 값이 손실되지 않습니다.


다음은 curl 예제에 사용되는 몇 가지 일반적인 예약된 키워드입니다. 이 목록은 전체 목록이 아니며 필요에 따라 추가 키워드가 사용됩니다. 그들의 의미는 상황에 따라 분명해야 합니다.

[cols="25,15,60"]
|===
| 키워드 | 유형 | 설명 


| account_ID>입니다 | 경로 | API 작업이 실행되는 계정을 식별하는 UIDv4 값입니다. 


| api_token> | 머리글 | 호출자를 식별하고 승인하는 베어러 토큰. 


| managed_app_ID> 를 선택합니다 | 경로 | API 호출에 대한 관리되는 응용 프로그램을 식별하는 UIDv4 값입니다. 
|===


== 워크플로 범주

배포 모델에 따라 두 가지 범주의 Astra 워크플로를 사용할 수 있습니다. Astra Control Center를 사용하는 경우 인프라 워크플로로 시작한 다음 관리 워크플로로 넘어가야 합니다. Astra Control Service를 사용하는 경우 일반적으로 관리 워크플로로 직접 이동할 수 있습니다.


NOTE: 워크플로의 curl 샘플은 Astra Control Service의 URL을 사용합니다. 사내 Astra Control Center를 사용하는 경우 해당 환경에 맞게 URL을 변경해야 합니다.



=== 인프라 워크플로우

이러한 워크플로우에서는 자격 증명, 버킷 및 스토리지 백엔드를 포함한 Astra 인프라를 처리합니다. Astra Control Center와 함께 필요하지만 대부분의 경우 Astra Control Service와 함께 사용할 수 있습니다. 워크플로우는 Astra 관리 클러스터를 설정하고 유지하는 데 필요한 작업에 중점을 둡니다.



=== 관리 워크플로

관리되는 클러스터가 있는 경우 이러한 워크플로우를 사용할 수 있습니다. 워크플로우는 애플리케이션 보호 및 관리 앱 백업, 복원, 클론 복제 등의 지원 작업에 중점을 둡니다.
